# fly.toml app configuration file generated for gridiron-guru on 2025-08-24T04:45:43Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gridiron-guru'
primary_region = 'ewr'
console_command = '/rails/bin/rails console'

[build]

[env]
  PORT=8080
  REDIS_URL="redis://default:4a663ae13f5545239a988c3a4d91279e@fly-gridiron-guru-redis.upstash.io:6379"

[processes]
  app = "bin/rails server -p 8080 -b 0.0.0.0"
  sidekiq = "bundle exec sidekiq"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

