# Sidekiq configuration
:verbose: false
:pidfile: tmp/pids/sidekiq.pid
:logfile: log/sidekiq.log
:concurrency: 5

# Redis configuration
:redis:
  url: redis://localhost:6379/0

# Queue configuration
:queues:
  - default
  - critical
  - sleeper_imports
  - low_priority

development:
  :verbose: true
  :concurrency: 2

production:
  :concurrency: 10
  :redis:
    url: <%= ENV.fetch("REDIS_URL", "redis://localhost:6379/0") %>

test:
  :concurrency: 1
  :redis:
    url: redis://localhost:6379/1